/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;
import java.util.HashMap;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        Map<String, String> person = new HashMap<>();
        person.put("name", "Maria");
        person.put("lastName", "Syrtseva");

        Gson gson = new Gson();
        String json = gson.toJson(person);
        System.out.println(json);
    }
}